# Production Profile Configuration
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

logging:
  level:
    root: WARN
    br.com.dio: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

server:
  error:
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    health:
      show-details: never
