# Development Profile Configuration
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: DEBUG
    br.com.dio: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

warehouse:
  security:
    jwt:
      secret: dev-secret-key-not-for-production-use-only
