# Development Profile Configuration
# This file contains ONLY non-sensitive development settings
# Sensitive values (passwords, secrets) must be in environment variables

spring:
  # Development Database (use environment variables for credentials)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:warehouse_db}
  
  # Show SQL for debugging
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Development logging (more verbose)
logging:
  level:
    root: INFO
    br.com.dio: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# RabbitMQ configuration (can be disabled for local dev)
rabbitmq:
  enabled: ${RABBITMQ_ENABLED:true}

# NOTE: User credentials are now stored in database (usuarios table)
# Migration V6 seeds dev users: admin, manager, sales
# Use DatabaseUserDetailsService for authentication (loaded from database)
